export const AMMINO_NAMES = {
  '1': 'Metionina',
  '2': 'Lisina',
  '3': 'Treonina',
  '4': 'Leucina',
  '5': 'Isoleucina',
  '6': 'Valina',
  '7': 'Fenilalanina',
  '8': 'Triptofano',
  '9': 'Taurina',
  '10': 'Arginina',
  '11': 'Istidina',
  '12': 'Alanina',
  '13': 'Aspartato',
  '14': 'Asparagina',
  '15': 'Glutamina',
  '16': 'Glutammato',
  '17': 'Cistina',
  '18': 'Glicina',
  '19': 'Tirosina',
  '20': 'Serina',
  '21': 'Prolina',
  '22': '3-Metilistidina',
  '23': 'Chinurenina',
  '24': 'Ornitina',
  '25': 'Citrullina',
  '26': 'Creatinina',
};
