export const METABOLOMICS_TABLES = [
  {
    groupId: 0,
    pageId: 0,
    sectionTitle: 'pdfpages.metabolomicstable.groups.0.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.0.title',
    metaIds: '1-2',
  },
  {
    groupId: 1,
    pageId: 0,
    title: 'pdfpages.metabolomicstable.groups.1.title',
    metaIds: '3-7',
  },
  {
    groupId: 2,
    pageId: 0,
    title: 'pdfpages.metabolomicstable.groups.2.title',
    metaIds: '8-15',
  },
  {
    groupId: 3,
    pageId: 1,
    sectionTitle: 'pdfpages.metabolomicstable.groups.3.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.3.title',
    metaIds: '16-19',
  },
  {
    groupId: 4,
    pageId: 1,
    title: 'pdfpages.metabolomicstable.groups.4.title',
    metaIds: '20-28',
  },
  {
    groupId: 5,
    pageId: 2,
    sectionTitle: 'pdfpages.metabolomicstable.groups.5.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.5.title',
    metaIds: '29-36',
  },
  {
    groupId: 6,
    pageId: 2,
    title: 'pdfpages.metabolomicstable.groups.6.title',
    metaIds: '37-40',
  },
  {
    groupId: 7,
    pageId: 2,
    title: 'pdfpages.metabolomicstable.groups.7.title',
    metaIds: '41-45',
  },
  {
    groupId: 8,
    pageId: 3,
    sectionTitle: 'pdfpages.metabolomicstable.groups.8.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.8.title',
    metaIds: '46-48',
  },
  {
    groupId: 9,
    pageId: 3,
    sectionTitle: 'pdfpages.metabolomicstable.groups.9.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.9.title',
    metaIds: '49-55',
  },
  {
    groupId: 10,
    pageId: 3,
    sectionTitle: 'pdfpages.metabolomicstable.groups.10.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.10.title',
    metaIds: '56-57',
  },
  {
    groupId: 11,
    pageId: 4,
    sectionTitle: 'pdfpages.metabolomicstable.groups.11.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.11.title',
    metaIds: '58-61',
  },
  {
    groupId: 12,
    pageId: 4,
    sectionTitle: 'pdfpages.metabolomicstable.groups.12.sectionTitle',
    title: 'pdfpages.metabolomicstable.groups.12.title',
    metaIds: '62-70',
  },
];
